
site_name: OT/IT Docs
site_description: Praktické how-to návody pro OT/IT integraci, bezpečnost a data
site_url: https://cy80r6.github.io/ot-it-docs/
repo_url: https://github.com/cy80r6/ot-it-docs
repo_name: cy80r6/ot-it-docs

theme:
  name: material
  language: cs
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cy80r6
  version:
    provider: mike

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - admonition
  - abbr
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.snippets
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

nav:
  - Úvod: index.md

  - How-to:
    - "Úvod do how-to": how-to/how-to.md
    - "Lab Quickstart (60 s)": how-to/lab-quickstart-60s.md
    - "Práce s docker-compose a Docker Desktop": how-to/prace-s-docker-compose.md
    - "Mosquitto: lokální vývojový profil": how-to/mosquitto-lokalni-profil.md
    - "ESP32 → MQTT v Pythonu (MicroPython)": how-to/esp32-micropython-mqtt.md
    - "ESP32 → MQTT (ESPHome)": how-to/esphome-esp32-mqtt.md
    - "ESP32 → MQTT (Tasmota)": how-to/tasmota-esp32-mqtt.md
    - "ESP32 → MQTT (PlatformIO/Arduino)": how-to/platformio-esp32-mqtt.md
    - "ESP32 → MQTT – varianty": how-to/esp32-mqtt-varianty.md
    - "CI-CD s GitHub Actions": how-to/ci-cd-github-actions.md
    - "CI-CD mike": how-to/ci-cd-mike.md
    - "CI-CD mkdocs": how-to/ci-cd-mkdocs-pages.md
    - "Instalace Docker + Compose": how-to/instalace-docker-compose.md
    - "Základní práce s kontejnery": how-to/zakladni-prace-s-kontejnery.md
    - "Instalace Mosquitto": how-to/instalace-mosquitto.md
    - "Instalace Node-RED": how-to/instalace-node-red.md
    - "Základní práce s Node-RED": how-to/zakladni-prace-s-node-red.md
    - "Node-RED zakladni flow": how-to/node-red-zakladni-flow.md
    - "MQTT Explorer": how-to/mqtt-explorer.md
    - "MQTT topic naming pro CNC": how-to/mqtt-topic-naming.md
    - "Návrh MQTT namespace": how-to/mqtt-namespace.md
    - "OPC UA → MQTT bridge": how-to/opcua-mqtt-bridge.md
    - "HiveMQ napojení": how-to/hivemq-napojeni.md
    - "InfluxDB instalace": how-to/influxdb-instalace.md
    - "Node-RED → InfluxDB": how-to/node-red-influxdb.md
    - "Node-RED dashboard (historie)": how-to/node-red-dashboard-historie.md
    - "Edge gateway: OPC UA → MQTT v Node-RED": how-to/edge-gateway-opcua-mqtt.md
    - "Mosquitto Security (TLS, auth, ACL, QoS)": how-to/mosquitto-security.md
    - "OPC UA SecureChannel": how-to/opcua-securechannel.md
    - "Šablona how-to": how-to/templates/how-to-template.md

  - Projekty:
    - "Sprint 0: Docker stack (Mosquitto + Node-RED)": projects/sprint-0-docker-stack.md
    - "Sprint 1: Lokální MQTT tok": projects/sprint-1-lokalni-mqtt-tok.md
    - "Sprint 2: OPC UA simulace + bridge do MQTT": projects/sprint-2-opcua-mqtt-bridge.md
    - "Projekt 3: MQTT do cloudu + historická data": projects/sprint-3-mqtt-cloud-influxdb.md
    - "Sprint 4: Základy bezpečnosti OT ↔ IT": projects/sprint-4-ot-it-security.md
    - "Docker base pro projekty": projects/docker-base-env.md
    - "Šablona projektu": projects/templates/project-template.md

  - Playbooks:
    - README: playbooks/README.md
    - "Runbook: Start/Stop labu": playbooks/runbook-lab-start.md
    - "OT/IT segmentace": playbooks/ot-it-segmentace.md

  - ADR:
    - "ADR 0001: Volba stacku": adr/adr-0001-volba-stacku.md
    - "ADR 0002: Docker stack jako výchozí prostředí": adr/adr-0002-docker-stack.md
    - "Šablona ADR": adr/adr-template.md

  - Reference:
    - "Slovníček pojmů":
        - "Slovníček pojmů (rozcestník)": reference/glossary.md
        - "ADR vysvětlivky": reference/adr-explanations.md
        - "LWT (Last Will and Testament) v MQTT": reference/mqtt-lwt.md
    - "Šablony":
        - "Šablona sprintu (použij jen při zakládání nového sprintu)": reference/templates/sprint_template.md
        - "Šablona how-to (použij jen při zakládání nového návodu)": reference/templates/howto_template.md
