
name: Release version with mike

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 0.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mike
          pip install pymdown-extensions
      - name: Deploy with mike
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mike deploy --push --update-aliases ${VERSION} latest
